services:
  blinmaster:
    image: denoland/deno
    container_name: blinmaster
    command: deno task start
    restart: always
    volumes:
      - .:/app
      - deno-cache:/deno-dir
    working_dir: /app
    environment:
      - DB_HOST=blinmaster-db
      - DB_PASSWORD=rzVMbBokFWui6mR6Eqeq7#segvT2fWGp
    ports:
      - "8001:8000"
    networks:
      - default
      - blinmaster

  blinmaster-db:
    image: mariadb
    container_name: blinmaster-db
    environment:
      MYSQL_ROOT_PASSWORD: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      MYSQL_DATABASE: blinmaster
      MYSQL_USER: blinmaster
      MYSQL_PASSWORD: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - blinmaster

  blinmaster-adminer:
    image: adminer
    container_name: bfpt-adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - default
      - blinmaster
    profiles:
      - adminer

volumes:
  deno-cache:
  db-data:

networks:
  default:
  blinmaster:
